"""Extract a fuzzing dictionary from the target's own source.

A coverage-guided fuzzer discovers `CREATE TABLE` by mutating bytes until it stumbles on it.
That is a long walk. libFuzzer's `-dict=` gives it the tokens up front, and the tokens are
sitting in the target's source as string literals — `sqlite3.c` contains every SQL keyword it
compares against, `libmagic` contains the type names it emits, `libxml2` contains its element
names.

This is not clever. It is the observation that a parser's vocabulary is written down inside
the parser, and that nobody has to guess it. The dictionary is emitted alongside the harness
and its effect is MEASURED by D8 like everything else — a dictionary that does not move
coverage is not kept on faith.

Deliberately conservative about what counts as a token: comparison strings and keywords are
useful, format strings and file paths are noise, and a dictionary full of noise costs the
fuzzer time rather than saving it.
"""
from __future__ import annotations

import re
from collections import Counter
from pathlib import Path
from typing import Iterable

# String literals, honouring escapes so `"a\"b"` is one token rather than two.
_STRING = re.compile(r'"((?:[^"\\\n]|\\.){2,64})"')

# Tokens that are about the program rather than about its input language.
_NOISE = re.compile(
    r"^(?:%|-|/|\.|\\)|"                      # format specifiers, flags, paths
    r"(?:%[sdiufxXpczln]|\\n|\\t|\\r)|"       # printf escapes
    r"^\w+\.(?:h|c|cc|cpp|hpp|inc)$|"          # file names, incl. sqlite3.h / fts5Int.h
    r"^\s*$|"
    r"^(?:out of memory|error|warning|assertion|unable to|cannot |failed)",
    re.I)

# Bare identifiers that are almost certainly C symbols rather than input vocabulary.
# Both of these are CASE-SENSITIVE on purpose. `_NOISE` carries re.IGNORECASE, and putting
# the camelCase rule in there made `[a-z]\w*[A-Z]\w*` match any alphabetic word at all —
# it silently deleted SELECT, WHERE and AND, which is the entire point of the dictionary.
_C_SYMBOL = re.compile(r"^[a-z_][a-z0-9_]*$")
_CAMEL = re.compile(r"^[a-z]\w*[A-Z]\w*$")          # aOrderBy, orderByConsumed


def _tokens_from(text: str) -> Iterable[str]:
    for m in _STRING.finditer(text):
        tok = m.group(1)
        if len(tok) < 2 or len(tok) > 64:
            continue
        if _NOISE.search(tok) or _CAMEL.match(tok):
            continue
        # Keep uppercase keywords (SQL, HTTP verbs), punctuation-bearing tokens, and mixed
        # forms. Drop bare lowercase identifiers, which are overwhelmingly C symbol names.
        if _C_SYMBOL.match(tok) and tok.upper() != tok:
            continue
        yield tok


def extract(sources: Iterable[str], limit: int = 512) -> list:
    """The most frequent input-vocabulary tokens in the target's source, most common first.

    Frequency is the ranking because a token the target compares against in many places is
    more likely to be part of its input language than a one-off message.
    """
    counts: Counter = Counter()
    for s in sources:
        p = Path(s)
        if not p.exists() or p.suffix not in (".c", ".cc", ".cpp", ".cxx", ".h", ".hpp"):
            continue
        try:
            counts.update(_tokens_from(p.read_text(errors="replace")))
        except OSError:
            continue
    return [t for t, _ in counts.most_common(limit)]


def render(tokens: Iterable[str]) -> str:
    """libFuzzer / AFL dictionary format: one `name="token"` per line."""
    out = ["# Generated by Harness Forge from the target's own string literals.",
           "# A parser's vocabulary is written down inside the parser.",
           "#",
           "# Its effect is measured by gate D8, not assumed: a dictionary that does not",
           "# move coverage should be dropped rather than kept out of politeness.",
           ""]
    for i, t in enumerate(tokens):
        esc = t.replace("\\", "\\\\").replace('"', '\\"')
        out.append(f'k{i}="{esc}"')
    return "\n".join(out) + "\n"


def write(sources: Iterable[str], path: Path, limit: int = 512) -> int:
    toks = extract(sources, limit)
    if not toks:
        return 0
    path.write_text(render(toks))
    return len(toks)
